# Generated by Django 4.2.7 on 2023-11-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(default='', max_length=500)),
                ('photo_main', models.ImageField(upload_to='photos/razas')),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(default='', max_length=500)),
                ('photo_main', models.ImageField(upload_to='photos/perros')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.raza')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
